[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "lettu_backend"
version = "0.1.0"
dependencies = ["fastapi", "uvicorn", "paho-mqtt"]

[tool.setuptools.packages.find]
where = ["src"]