[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "lettu_vault_ai"
version = "0.1.0"
dependencies = ["ultralytics", "opencv-python", "torch", "numpy"]

[tool.setuptools.packages.find]
where = ["src"]